### ISSUE TITLE
Can't figure out glitch with knights

### ISSUE THREAD

**Issue by emmahogan** [emmahogan/225FinalProject#3]
Dr. Teresco - we are having this glitch with moving the knights where the possible moves are updating correctly, and the location of the knight is prints the correct square, but the piece doesn't update. We have been stuck on this for so long, if you get the chance to take a look we would appreciate it

**Comment by jteresco** [comment]
Can you point me to some specific places in the code where this should be happening?

**Comment by emmahogan** [comment]
We finally fixed it - the squares were referencing other squares
